### ISSUE TITLE
Recommend making LimitException Recommended instead of Mandatory

### ISSUE THREAD

**Issue by mgarrett33** [opencomputeproject/OCP-Profiles#2]
Power limit exception (`LimitException`) is not always implemented as a capability for power capping.  Its probably not universally implemented enough to call it mandatory.  I would recommend we make this property recommended instead of mandatory.

**Comment by jcleung5549** [comment]
Details from the schema file (Power_v1.xml)

<ComplexType Name="PowerLimit">
        <Annotation Term="OData.LongDescription" String="This type shall contain power limit status and configuration information for this chassis."/>
        <Property Name="LimitInWatts" Type="Edm.Decimal">
          <Annotation Term="OData.Permissions" EnumMember="OData.Permission/ReadWrite"/>
          <Annotation Term="OData.LongDescription" String="The value of this property shall represent the power cap limit in watts for the resource.  If set to null, power capping shall be disabled."/>
          <Annotation Term="Measures.Unit" String="W"/>
          <Annotation Term="Validation.Minimum" Int="0"/>
        </Property>
        <Property Name="LimitException" Type="Power.v1_0_0.PowerLimitException">
          <Annotation Term="OData.Permissions" EnumMember="OData.Permission/ReadWrite"/>
          <Annotation Term="OData.LongDescription" String="The value of this property shall represent the action to be taken if the resource power consumption can not be limited below the specified limit after several correction time periods."/>
        </Property>
        <Property Name="CorrectionInMs" Type="Edm.Int64">
          <Annotation Term="OData.Permissions" EnumMember="OData.Permission/ReadWrite"/>
          <Annotation Term="OData.LongDescription" String="The value of this property shall represent the time interval in ms required for the limiting process to react and reduce the power consumption below the limit."/>
          <Annotation Term="Measures.Unit" String="ms"/>
        </Property>
</ComplexType>

<EnumType Name="PowerLimitException">
        <Member Name="NoAction">
          <Annotation Term="OData.Description" String="Take no action when the limit is exceeded."/>
        </Member>
        <Member Name="HardPowerOff">
          <Annotation Term="OData.Description" String="Turn the power off immediately when the limit is exceeded."/>
        </Member>
        <Member Name="LogEventOnly">
          <Annotation Term="OData.Description" String="Log an event when the limit is exceeded, but take no further action."/>
        </Member>
        <Member Name="Oem">
          <Annotation Term="OData.Description" String="Take an OEM-defined action."/>
        </Member>
</EnumType>

**Comment by mgarrett33** [comment]
After further discussion and noting the limited scope of the requirement, we’re recommending to close this issue with no fix needed.
