### ISSUE TITLE
Replace IndicatorLED with LocationIndicatorActive

### ISSUE THREAD

**Issue by gtmills** [opencomputeproject/OCP-Profiles#22]
Hi, 
Gunnar here from the OpenBMC project. Redfish moved away from IndicatorLED to LocationIndicatorActive in 2020.3. 
More information can be found at http://www.dmtf.org/sites/default/files/Redfish_Release_2020.3_Overview.pdf

https://github.com/opencomputeproject/OCP-Profiles/search?q=IndicatorLED&type=

**Comment by jcleung5549** [comment]
Change profile to allow either IndicatorLED or LocationIndicatorActive property.

**Comment by jcleung5549** [comment]
Closed
