### ISSUE TITLE
Profiles fail JSON schema validation

### ISSUE THREAD

**Issue by jautor** [opencomputeproject/OCP-Profiles#8]
Base and Server profiles both fail JSON schema validation due to an incorrect (was a pre-v1.0 definition) property name within `ActionRequirements` - `MinSupportValues` or `AllowableValues` should be `ParameterValues`.  

Also, the `Purpose` in one of the actions is within the parameter object instead of at the Action level.

**Comment by JojoWu19** [comment]
In the OCPBaselineHardwareManagement.v1_0_1.json, it doesn't include #7 and validator reports error.
